export default function page() {
  return (
    <div className="flex flex-col items-center flex-1">
        <h2 className="font-bold mt-11 mb-4 text-white text-2xl md:text-4xl ">About Page</h2>
        <p className="text-white w-[1050px] max-w-xs p-4 tiny:max-w-sm text-base sm:text-lg sm:max-w-lg md:max-w-2xl lg:max-w-4xl text-left">Welcome to our website, the ultimate destination for technology sentiment analysis and statistics. Our site is dedicated to providing a comprehensive and reliable source of information on how people feel about the latest technologies. With 47,000 data points collected from Twitter, we offer a unique insight into the technological landscape and how it is perceived by the general public.</p>
        <p className="text-white w-[1050px] max-w-xs p-4 tiny:max-w-sm text-base sm:text-lg sm:max-w-lg md:max-w-2xl lg:max-w-4xl text-left">Our team has worked tirelessly to gather and analyze this data, which is mostly from the end of 2022 and the beginning of 2023.</p>
        <p className="text-white w-[1050px] max-w-xs p-4 tiny:max-w-sm text-base sm:text-lg sm:max-w-lg md:max-w-2xl lg:max-w-4xl text-left">Whether you are a tech enthusiast, investor, or simply curious about the latest trends, our website has something for you. Our data is presented in an easy-to-read format, with interactive graphs and charts that let you explore and compare different technologies. We also provide valuable insights and analysis on the latest technological advancements, including emerging trends and market trends.</p>
        <p className="text-white w-[1050px] max-w-xs p-4 tiny:max-w-sm text-base sm:text-lg sm:max-w-lg md:max-w-2xl lg:max-w-4xl text-left">Stay ahead of the curve by exploring our data and discover what the world thinks about the technology that drives our lives. With our website, you will have access to the latest and most comprehensive technology sentiment analysis data available.</p>
        <h2 className="font-bold mt-11 mb-4 text-white text-xl md:text-2xl">Considerations</h2>
        <p className="text-white w-[1050px] max-w-xs p-4 tiny:max-w-sm text-base sm:text-lg sm:max-w-lg md:max-w-2xl lg:max-w-4xl text-left">We understand that Twitter may not be the most representative or the best way to quantify how people might truly feel about a technology. One step we took to ensure data quality is the collection of only positive and negative sentiment tweets, to ensure that tweets like Advent of Code or job listings do not affect results.</p>
        <p className="text-white w-[1050px] max-w-xs p-4 tiny:max-w-sm text-base sm:text-lg sm:max-w-lg md:max-w-2xl lg:max-w-4xl text-left">Something else that should be considered is that the popularity of a tech may affect its sentiment. Examples of this are Angular and Ember. Also, as with most reviews, satisfied customers or users of a product may not take the time to communicate their satisfaction.</p>
        <h2 className="font-bold mt-11 mb-4 text-white text-xl md:text-2xl">Process</h2>
        <p className="mb-11 text-white w-[1050px] max-w-xs p-4 tiny:max-w-sm text-base sm:text-lg sm:max-w-lg md:max-w-2xl lg:max-w-4xl text-left">Made by Kyle Leung and Wesley Nguyen as a personal project. The frontend was architected using Next.js, the backend using Rust, and data was acquired using Python and the amazing snscrape library. All the data is stored within a MongoDB cluster.</p>
    </div>
  )
}